// Code generated by "stringer -type Subtype"; DO NOT EDIT.

package css

import "strconv"

const _Subtype_name = "SubtypeNoneSubtypeIDSubtypeNumberSubtypeInteger"

var _Subtype_index = [...]uint8{0, 11, 20, 33, 47}

func (i Subtype) String() string {
	if i >= Subtype(len(_Subtype_index)-1) {
		return "Subtype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Subtype_name[_Subtype_index[i]:_Subtype_index[i+1]]
}
