// Code generated by "stringer -type Token"; DO NOT EDIT.

package css

import "strconv"

const _Token_name = "UnknownEOFIdentFunctionAtKeywordHashStringBadStringURLBadURLDelimNumberPercentageDimensionUnicodeRangeIncludeMatchDashMatchPrefixMatchSuffixMatchSubstringMatchColumnCDOCDCColonSemicolonCommaLeftBrackRightBrackLeftParenRightParenLeftBraceRightBrace"

var _Token_index = [...]uint8{0, 7, 10, 15, 23, 32, 36, 42, 51, 54, 60, 65, 71, 81, 90, 102, 114, 123, 134, 145, 159, 165, 168, 171, 176, 185, 190, 199, 209, 218, 228, 237, 247}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
