// Code generated by "stringer -type Token -linecomment"; DO NOT EDIT.

package css

import "strconv"

const _Token_name = "UnknownEOFIdentFunctionAtKeywordHashStringBadStringURLBadURLDelimNumberPercentageDimensionUnicodeRangeIncludeMatchDashMatchPrefixMatchSuffixMatchSubstringMatchColumn<!---->:;,[](){}"

var _Token_index = [...]uint8{0, 7, 10, 15, 23, 32, 36, 42, 51, 54, 60, 65, 71, 81, 90, 102, 114, 123, 134, 145, 159, 165, 169, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
