// Code generated by "stringer -type TypeFlag"; DO NOT EDIT.

package css

import "strconv"

const _TypeFlag_name = "TypeFlagNoneTypeFlagIDTypeFlagNumberTypeFlagInteger"

var _TypeFlag_index = [...]uint8{0, 12, 22, 36, 51}

func (i TypeFlag) String() string {
	if i >= TypeFlag(len(_TypeFlag_index)-1) {
		return "TypeFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeFlag_name[_TypeFlag_index[i]:_TypeFlag_index[i+1]]
}
