// Code generated by "stringer -type ValueType -linecomment"; DO NOT EDIT.

package css

import "strconv"

const _ValueType_name = "ValueUknownidentfunctionhashhash-idstringurldelimnumintpercentdimunicode-rangeinclude-matchdash-matchprefix-matchsuffix-matchsubstr-matchcomma"

var _ValueType_index = [...]uint8{0, 11, 16, 24, 28, 35, 41, 44, 49, 52, 55, 62, 65, 78, 91, 101, 113, 125, 137, 142}

func (i ValueType) String() string {
	if i < 0 || i >= ValueType(len(_ValueType_index)-1) {
		return "ValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
